version: "3.9"
services:
  app1_service:
    container_name: app1
    build: ./app1
    volumes:
      - ./app1:/app
    environment:
      APP_PORT: 8000
    ports:
      - "8000:8000"
    restart: always
  app2_service:
    container_name: app2
    build: ./app2
    volumes:
      - ./app2:/app
    environment:
      APP_PORT: 8001
    ports:
      - "8001:8001"
    restart: always

networks:
  default:
    name: app_custom_network